Minor Fix

diff --git a/.github/workflows/python-release.yml b/.github/workflows/python-release.yml
--- a/.github/workflows/python-release.yml
+++ b/.github/workflows/python-release.yml
@@ -30,6 +30,11 @@ jobs:
       - name: Create executable with PyInstaller
         run: |
           pyinstaller --onefile --distpath dist --workpath build --specpath spec WallpaperDownloader.py
+          
+      # Verificar si el archivo .exe se generó correctamente
+      - name: Verify the .exe file
+        run: |
+          if [ -f dist/WEWD.exe ]; then echo "Executable created successfully"; else echo "Error: Executable not found!"; exit 1; fi
 
       # Paso 5: Crea el archivo ZIP con el .exe y otros archivos
       - name: Create ZIP file
